### ISSUE TITLE
Paypal Issues

### ISSUE THREAD

**Issue by FranRoy** [GetResponse/GetResponse-Magento_2-Integration#4]
Hello,

Have you tested the module using Paypal gateway? It gives a parameter error (expects parameter 1 to be array) on SubscribeFromOrder.php (line 63) and the order is not placed on magento.

Best Regards,

Fran.

**Comment by FranRoy** [comment]
Hello?

**Comment by amodliszewski** [comment]
Hi,

We did not tested our module with Paypal gateway. We will check on that.

**Comment by jsypolt** [comment]
Any update on this? We currently cannot use GetResponse integration because it breaks PayPal payments. In addition to the error message noted above, this also causes the Magento Order ID -> Invoice IDs to the thrown off and all future PayPal payments start failing, even with this module removed because Invoice IDs that already exist start being sent to PayPal.

**Comment by rkarkut** [comment]
We are working on this problem right now. I will let you know when it will be fixed.

**Comment by amodliszewski** [comment]
We send fix for our observer that should solve this problem.
